import { mkdir, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import path from "node:path";

function nginxEscape(value) {
  return String(value).replace(/\\/g, "\\\\").replace(/;/g, "");
}

export function renderNginxRouteMap(routes) {
  const active = routes
    .filter((route) => route.status === "active" && route.host && route.targetHost && route.targetPort)
    .sort((a, b) => a.host.localeCompare(b.host));

  const lines = [
    "# Generated by SISP AppHub. Do not edit by hand.",
    "map $host $apphub_upstream {",
    "    default \"\";"
  ];
  for (const route of active) {
    lines.push(`    ${nginxEscape(route.host)} http://${nginxEscape(route.targetHost)}:${Number(route.targetPort)};`);
  }
  lines.push("}");
  lines.push("");
  return `${lines.join("\n")}`;
}

function runReload(command) {
  if (!command) return Promise.resolve();
  return new Promise((resolve, reject) => {
    const child = spawn(command, { shell: true, stdio: "ignore" });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`Route reload command exited with code ${code}.`));
    });
  });
}

export async function syncNginxRoutes(config, store) {
  if (!config.nginxRouteMapPath) return { skipped: true };
  const routes = await store.listRoutes();
  const body = renderNginxRouteMap(routes);
  await mkdir(path.dirname(config.nginxRouteMapPath), { recursive: true });
  await writeFile(config.nginxRouteMapPath, body, "utf8");
  await runReload(config.nginxReloadCommand);
  return { skipped: false, routeCount: routes.filter((route) => route.status === "active").length };
}
